
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airports
    username: postgres
    password: mchforever93

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true





